#!/usr/bin/env python3
"""Materialize canonical manuscript figure inputs from full Lake Erie reruns.

This script is intentionally fail-closed. It expects the *full* individual-level
outputs generated by:
  analysis/09_lake_erie_state_fidelity.py
  analysis/12_lake_erie_availability_coupling.py
  analysis/13_lake_erie_buffering_limits.py

It validates their aggregate values against:
  manuscript/MANUSCRIPT_NUMERIC_CONTRACT_V2.json

before writing manuscript/figure_data/*.csv.

Run only after the full analyses have been rerun in an environment that can
access the public Zenodo release.
"""
from __future__ import annotations

import csv
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATE = ROOT / "results" / "lake_erie_state_fidelity_v1.json"
COUPLING = ROOT / "results" / "lake_erie_availability_coupling_v1.json"
LIMITS = ROOT / "results" / "lake_erie_buffering_limits_v1.json"
CONTRACT = ROOT / "manuscript" / "MANUSCRIPT_NUMERIC_CONTRACT_V2.json"
OUT = ROOT / "manuscript" / "figure_data"


def close(a: float, b: float, tol: float = 5e-6) -> bool:
    return math.isclose(float(a), float(b), rel_tol=0.0, abs_tol=tol)


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise RuntimeError(f"refusing to write empty figure table: {path}")
    fields = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def main() -> None:
    state = json.loads(STATE.read_text(encoding="utf-8"))
    coupling = json.loads(COUPLING.read_text(encoding="utf-8"))
    limits = json.loads(LIMITS.read_text(encoding="utf-8"))
    contract = json.loads(CONTRACT.read_text(encoding="utf-8"))

    # Full rerun guardrails: canonical summary-only files are not sufficient.
    require(
        isinstance(state.get("primary_sri", {}).get("individuals"), list),
        "state-fidelity result lacks primary_sri.individuals; rerun analysis/09 first",
    )
    require(
        isinstance(
            state.get("primary_temporal_state_retention", {}).get("individuals"), list
        ),
        "state-fidelity result lacks temporal individual rows; rerun analysis/09 first",
    )
    require(
        isinstance(coupling.get("primary", {}).get("individuals"), list),
        "coupling result lacks primary.individuals; rerun analysis/12 first",
    )
    require(
        isinstance(limits.get("individuals"), list),
        "buffering-limits result lacks individuals; rerun analysis/13 first",
    )

    # Validate aggregate state-fidelity rerun against manuscript contract.
    ps = state["primary_sri"]["summary"]
    ts = state["primary_temporal_state_retention"]["summary"]
    strict_s = state["strict_two_random_sri"]["summary"]
    strict_t = state["strict_two_random_temporal_state_retention"]["summary"]

    require(int(ps["n_birds"]) == contract["qc"]["birds"], "bird count drift")
    require(
        int(ps["total_events"]) == contract["qc"]["valid_matched_events"],
        "matched-event count drift",
    )
    require(close(ps["median_retention"], contract["primary_sri"]["median"]), "SRI median drift")
    require(close(ps["mean_retention"], contract["primary_sri"]["mean"]), "SRI mean drift")
    require(
        close(ts["median_retention"], contract["temporal_state_retention"]["median"]),
        "temporal-retention median drift",
    )
    require(
        int(strict_s["total_events"]) == contract["qc"]["strict_two_random_events"],
        "strict two-random event count drift",
    )
    require(
        close(strict_s["median_retention"], contract["strict_two_random_sri"]["median"]),
        "strict SRI median drift",
    )
    require(
        close(
            strict_t["median_retention"],
            contract["strict_two_random_temporal_retention"]["median"],
        ),
        "strict temporal-retention median drift",
    )

    cp = coupling["primary"]["pooled_within_bird"]
    cc = contract["availability_coupling"]["primary"]
    require(close(cp["observed_slope"], cc["observed_slope"]), "coupling slope drift")
    require(
        close(cp["pseudo_null_median_slope"], cc["pseudo_null_median_slope"]),
        "coupling null median drift",
    )
    require(
        close(cp["coupling_reduction"], cc["coupling_reduction"]),
        "coupling reduction drift",
    )

    lp = limits["primary"]
    lc = contract["buffering_limits"]
    require(
        close(lp["pooled_within_bird_abs_deviation_slope"], lc["pooled_abs_deviation_slope"]),
        "buffering-limit slope drift",
    )
    require(
        close(lp["pseudo_null_median_slope"], lc["pseudo_null_median_slope"]),
        "buffering-limit null drift",
    )
    require(
        close(lp["coupling_reduction"], lc["coupling_reduction"]),
        "buffering-limit reduction drift",
    )

    # Figure 2: merge the four per-bird state-retention families.
    primary_sri = {x["individual_id"]: x for x in state["primary_sri"]["individuals"]}
    strict_sri = {x["individual_id"]: x for x in state["strict_two_random_sri"]["individuals"]}
    primary_tr = {
        x["individual_id"]: x
        for x in state["primary_temporal_state_retention"]["individuals"]
    }
    strict_tr = {
        x["individual_id"]: x
        for x in state["strict_two_random_temporal_state_retention"]["individuals"]
    }

    bird_ids = sorted(primary_sri)
    require(
        set(bird_ids) == set(strict_sri) == set(primary_tr) == set(strict_tr),
        "individual IDs differ among state-retention reruns",
    )

    fig2 = []
    for bird in bird_ids:
        s = primary_sri[bird]
        ss = strict_sri[bird]
        tr = primary_tr[bird]
        st = strict_tr[bird]
        fig2.append({
            "individual_id": bird,
            "n_events": s["n_events"],
            "sri": s["retention"],
            "sri_null_median_variance": s["null_median"],
            "sri_monte_carlo_p": s["monte_carlo_add_one_p"],
            "temporal_retention": tr["retention"],
            "temporal_null_median_change": tr["null_median"],
            "temporal_monte_carlo_p": tr["monte_carlo_add_one_p"],
            "strict_two_random_events": ss["n_events"],
            "strict_sri": ss["retention"],
            "strict_temporal_retention": st["retention"],
        })
    write_csv(OUT / "fig2_individual_state_retention.csv", fig2)

    # Figure 3A/B: aggregate coupling conditions.
    fig3_summary = []
    for key, label in (
        ("primary", "primary"),
        ("conditional_flooded", "random_points_flooded"),
        ("all_points_flooded", "all_points_flooded"),
    ):
        x = coupling[key]
        p = x["pooled_within_bird"]
        fig3_summary.append({
            "condition": label,
            "events": x["events"],
            "birds": x["birds"],
            "observed_slope": p["observed_slope"],
            "pseudo_null_median_slope": p["pseudo_null_median_slope"],
            "coupling_reduction": p["coupling_reduction"],
            "monte_carlo_p_lower": p["monte_carlo_add_one_p_lower"],
        })
    write_csv(OUT / "fig3_coupling_summary.csv", fig3_summary)

    # Figure 3C: per-bird primary coupling.
    fig3_ind = []
    for x in coupling["primary"]["individuals"]:
        fig3_ind.append({
            "individual_id": x["individual_id"],
            "n_events": x["n_events"],
            "observed_slope": x["observed_used_on_availability_slope"],
            "pseudo_null_median_slope": x["pseudo_null_median_slope"],
            "coupling_reduction": x["coupling_reduction"],
            "monte_carlo_p_lower": x["monte_carlo_add_one_p_lower"],
        })
    require(
        {x["individual_id"] for x in fig3_ind} == set(bird_ids),
        "coupling individual IDs differ from SRI IDs",
    )
    write_csv(OUT / "fig3_individual_coupling.csv", sorted(fig3_ind, key=lambda x: x["individual_id"]))

    # Figure 4: already-canonical individual buffering-limit rows.
    fig4 = []
    for x in limits["individuals"]:
        fig4.append({
            "individual_id": x["individual_id"],
            "n_events": x["n_events"],
            "median_available_depth": x["median_available_depth"],
            "median_used_depth": x["median_used_depth"],
            "mismatch_q75": x["mismatch_q75"],
            "extreme_events": x["extreme_events"],
            "slope_buffering": x["slope_buffering"],
            "extreme_retention": x["extreme_retention"],
            "extreme_lower_tail_p": x["extreme_lower_tail_p"],
        })
    require(
        {x["individual_id"] for x in fig4} == set(bird_ids),
        "buffering-limit individual IDs differ from SRI IDs",
    )
    write_csv(OUT / "fig4_individual_buffering_limits.csv", sorted(fig4, key=lambda x: x["individual_id"]))

    # Supplementary sample flow.
    q = contract["qc"]
    sample_flow = [
        {"stage": "source_rows", "n": q["source_rows"]},
        {"stage": "source_missing_excluded", "n": q["missing_yes_excluded"]},
        {"stage": "malformed_id_excluded", "n": q["malformed_ids_excluded"]},
        {"stage": "valid_matched_events", "n": q["valid_matched_events"]},
        {"stage": "strict_two_random_events", "n": q["strict_two_random_events"]},
        {"stage": "individual_birds", "n": q["birds"]},
    ]
    write_csv(OUT / "supp_sample_flow.csv", sample_flow)

    metadata = {
        "schema": "louis.figure_data.v1",
        "source_results": {
            "state_fidelity": str(STATE.relative_to(ROOT)),
            "availability_coupling": str(COUPLING.relative_to(ROOT)),
            "buffering_limits": str(LIMITS.relative_to(ROOT)),
            "numeric_contract": str(CONTRACT.relative_to(ROOT)),
        },
        "monte_carlo": {
            "state_base_seed": state.get("base_seed"),
            "state_replicates_per_bird": state.get("replicates_per_bird"),
            "coupling": coupling.get("monte_carlo", {
                "base_seed": 20261003,
                "individual_replicates": 20000,
                "pooled_replicates": 20000,
            }),
        },
        "reporting_boundary": [
            "Individual bird is the biological replication unit.",
            "Do not infer that measured geographic displacement caused buffering.",
            "Lake Erie SRI is the primary independent result; buffering-limit analyses are post-hoc decomposition.",
        ],
    }
    (OUT / "figure_metadata.json").write_text(
        json.dumps(metadata, indent=2), encoding="utf-8"
    )
    print(f"wrote figure data to {OUT}")


if __name__ == "__main__":
    main()
