#!/usr/bin/env python3
"""Reference renderer entry point for Louisiana manuscript figures.

Canonical input tables are in manuscript/figure_data/ and are generated by
analysis/14_build_manuscript_figure_data.py from full public-data reruns.

The repository commits deterministic SVG reference renders in:
  manuscript/rendered_figures/

Numeric content is locked by:
  manuscript/MANUSCRIPT_NUMERIC_CONTRACT_V2.json
  manuscript/FIGURE_DATA_CONTRACT_V2.json

Do not render 190 events as independent biological replicates; figures use
individual birds as the inferential display unit.
"""
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
FIG=ROOT/"manuscript"/"rendered_figures"

def main():
    required=[
        ROOT/"manuscript"/"figure_data"/"fig2_individual_state_retention.csv",
        ROOT/"manuscript"/"figure_data"/"fig3_coupling_summary.csv",
        ROOT/"manuscript"/"figure_data"/"fig3_individual_coupling.csv",
        ROOT/"manuscript"/"figure_data"/"fig4_individual_buffering_limits.csv",
    ]
    missing=[str(p.relative_to(ROOT)) for p in required if not p.exists()]
    if missing:
        raise SystemExit("missing canonical figure tables: "+", ".join(missing))
    rendered=[FIG/f"Figure{i}.svg" for i in range(1,6)]
    missing_render=[str(p.relative_to(ROOT)) for p in rendered if not p.exists()]
    if missing_render:
        raise SystemExit("missing committed reference SVGs: "+", ".join(missing_render))
    print("Louisiana canonical figure tables and reference SVGs: present")

if __name__=="__main__":
    main()
